name: google_directions_api_example
description: Example command line application of google_directions_api package.

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  google_directions_api:
    path: ../
